eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
spring:
  boot:
    admin:
      api-path: instances
      url: http://localhost:7200
management:
  security:
    enabled: false

