spring:
  profiles:
    active: dev,basedev
  application:
    name: zuul
server:
  port: 8000
zuul:
  routes:
    oauth:
      sensitiveHeaders:
      path: /uaa/**
      serviceId: oauth

    api:
      sensitiveHeaders:
      path: /api/**
      serviceId: api-service
  add-proxy-headers: true

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
