
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8100/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
  server:
    enable-self-preservation: false
