spring:
  profiles:
    active: dev,basedev
  application:
    name: api-service
  jackson:
    default-property-inclusion: non_null
server:
  port: 8300
security:
  oauth2:
    resource:
      id: api-service
      user-info-uri: http://localhost:8200/user
      prefer-token-info: true