spring:
  profiles:
    active: dev,basedev
  application:
    name: api-service
  jackson:
    default-property-inclusion: non_null
server:
  port: 8300
security:
  oauth2:
    resource:
      id: api-service
      user-info-uri: http://localhost:8200/user
      prefer-token-info: true
  user:
    name: api
    password: api
#在线查看日志
endpoints:
  logfile:
    enabled: true
  shutdown:
    enabled: true
management:
  security:
    enabled: false


